Added custom User class, also called User.
This will fail with the following errors:

```bash
[berto@g6]$ python manage.py syncdb --noinput
CommandError: One or more models did not validate:
someapp.user: Accessor for m2m field 'groups' clashes with related m2m
field 'Group.user_set'. Add a related_name argument to the definition
for 'groups'.
someapp.user: Accessor for m2m field 'user_permissions' clashes with
related m2m field 'Permission.user_set'. Add a related_name argument to
the definition for 'user_permissions'.
auth.user: Accessor for m2m field 'groups' clashes with related m2m
field 'Group.user_set'. Add a related_name argument to the definition
for 'groups'.
auth.user: Accessor for m2m field 'user_permissions' clashes with
related m2m field 'Permission.user_set'. Add a related_name argument to
the definition for 'user_permissions'.
```